[package]
name = "ivn-forwarder"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
encoding_rs = "0.8.34"
encoding_rs_io = "0.1.7"
glob = "0.3.1"
prometheus = "0.13.4"
prometheus_exporter = "0.8.5"
regex = "1.10.6"
